# Generated by Django 3.1.4 on 2020-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201222_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='def status', max_length=50, verbose_name='Status'),
        ),
    ]
